# Generated by Django 4.2.2 on 2023-07-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transcript_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CourseCredit',
            new_name='course_credit',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CourseID',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CourseName',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Description',
            new_name='description',
        ),
    ]
