# Generated by Django 4.2.2 on 2023-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_coursecredit_course_course_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=10),
        ),
    ]
