# Generated by Django 4.2.2 on 2023-08-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='Classroom',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Instructor',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='NumberOfStudents',
            new_name='number_of_students',
        ),
    ]
