# Generated by Django 4.2.2 on 2023-07-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciesza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ciesza.submission'),
        ),
    ]
