# Generated by Django 4.2.2 on 2023-07-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transcript_grade'),
        ('ciesza', '0003_submission_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.course'),
        ),
    ]
