# Generated by Django 4.2.2 on 2023-07-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciesza', '0004_alter_submission_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
    ]
