# Generated by Django 4.2.2 on 2023-07-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transcript_grade'),
        ('ciesza', '0005_remove_comment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_submissions', to='accounts.profile'),
        ),
    ]
