# Generated by Django 4.2.2 on 2023-08-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_nickname'),
        ('ciesza', '0008_alter_comment_text_alter_submission_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='accounts.profile'),
        ),
    ]
